version: '3'
networks:
  app-network:

services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user=sammy 
        - uid=1004             
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:80'            
    links:
      - 'app'
    volumes:
      - './:/var/www'
      - './nginx:/etc/nginx/conf.d'
    depends_on:
      - app
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - database:/var/lib/mysql/      
  
    networks:
      - app-network

#Volumes
volumes:
  database:
    driver: local

   